### ISSUE TITLE
Build with older SDK for Apple M1

### ISSUE THREAD

**Issue by leet4tari** [tari-project/randomx-rs#48]
Due to bug https://github.com/tevador/RandomX/issues/262#issuecomment-1543655280, we need to build randomx with older MacOS SDK on ARM64 hardware.

**Comment by leet4tari** [comment]
if we can pass the location of the SDK to cmake at the time of build, we should be able to work around the bug. Would need an older XCode and/or MacOS SDK installed.

**Comment by leet4tari** [comment]
Added a note to README.md, need to check this all works in a GHA workflow.

**Comment by selsta** [comment]
Fixed in https://github.com/tevador/RandomX/pull/281
